# Generated by Django 2.2.11 on 2020-03-30 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamer_app', '0002_auto_20200331_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='published_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='published_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
